---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
mainfont: {Arial Unicode MS}
---

```{r setup, include=FALSE}
knitr::asis_output("\U207A","\U2212")
```

### **NSCLC** : 


**Figure 1 and Supplementary Figure 2**

* Characterize stroma cells (CD90`r knitr::asis_output("\U207A")` and CD90`r knitr::asis_output("\U2212")` fibroblasts and endothelial cells (EC) and primarily focus on CCL19`r knitr::asis_output("\U207A")` fibroblasts : [NSCLC_stroma_CCCL19_FRC.html](NSCLC_stroma_CCCL19_FRC.html)  

* Compare NSCLC CCL19 FRCs with Tonsilar FRCs :
[NSCLC_vs_Tonsils.html](NSCLC_vs_Tonsils.html)

* Compare NSCLC CCL19 FRCs with NSCLC and BRCA CAFs :
[NSCLC_vs_BRCA_CAFs.html](NSCLC_vs_BRCA_CAFs.html)


**Figure 3 and Supplementary Figure 3**

* Characterize and visualize Tumor infiltrating lymphocytes (TILs), with a focus on CD8`r knitr::asis_output("\U207A")` T cell subsets : [NSCLC_TILS.html](NSCLC_TILS.html)

* Combine NSCLS CCL19`r knitr::asis_output("\U207A")` FRCs and NSCLS TILs (special focus on CD8`r knitr::asis_output("\U207A")` T cells ) and perform interactome analysis to determine significant signaling L-R pairs and genes involved : [merge_NSCLC_FRC_TIL.html](merge_NSCLC_FRC_TIL.html)


**Figure 4 and Supplementary Figure 4**

* NSCLC differentiation: [NSCLC_trajectory_analysis.html](NSCLC_trajectory_analysis.html)


### **Protocol to investigate fibroblastic reticular cell-immune cell interaction in human lung cancer**

**Figure 3**

* Characterize CAFs and TILs in NSCLC : [FRC_TIL_landscape.html](FRC_TIL_landscape.html)

**Figure 4**

* Define CCL19`r knitr::asis_output("\U207A")` FRC subsets in NSCLC and infer their intercellular communication with immune cells  : [comparison_CCL19_FRC_NSCLC_tonsil.html](comparison_CCL19_FRC_NSCLC_tonsil.html)


### **Murine Lung Tumors** :


**Figure 5**

* Characterize CCL19-EYFP`r knitr::asis_output("\U207A")` cell data from naïve lungs and excised LLC-gp33 tumors on day 23 : [Mouse_LLC_naive.html](Mouse_LLC_naive.html)


**Figure 6 and Supplementary Figure 5**

* Characterize CCL19-EYFP`r knitr::asis_output("\U207A")` FRC subsets in coronavirus-vector based immunotherapy : [Mouse_mCOV.html](Mouse_mCOV.html)


**Figure 7, Supplementary Figure 5 and Supplementary Figure 6**

* Characterize GP33/34`r knitr::asis_output("\U207A")` CD8`r knitr::asis_output("\U207A")` T cells sorted from LLC-gp33 bearing DTR`r knitr::asis_output("\U207A")` and DTR$^`r knitr::asis_output("\U2212")`$ lungs on day 23, after mCOV-Flt3l-gp33 immunization : [Tetra_CD8_T_cells.html](Tetra_CD8_T_cells.html)

* Characterize total CD8 T cells in DTR lungs and perform interactome analysis between TLS TRC, Sulf1⁺ TRC and Tetramer⁺ CD8⁺ T cells : [Total_CD8_DTR_Tetra.html](Total_CD8_DTR_Tetra.html)

* Comparison of naive CCL19-EYFP cells vs mCOV-FIt31-g33 CCL19-EYFP cells : [mcov_R.html](mcov_R.html)


